### ISSUE TITLE
great project, some advice

### ISSUE THREAD

**Issue by LiquidFenrir** [reworks/3DS_eBook_Reader#4]
Hello! Saw your post on 3dshacks, looks cool. haven't tried the app yet but nice job for releasing!
Noticed a few things in the code though so here is some advice:

In App.cpp : you don't need to do sdmcInit, aptInit, and hidInit. it's already done by ctrulib https://github.com/smealum/ctrulib/blob/master/libctru/source/system/appInit.c

Also, lines 78-81 and 90-93: you should be using pp2d_draw_on rather than end and begin again. that can cause problems

**Comment by reworks-org** [comment]
Thanks for the pp2d fixes.

I'm not worried about calling appInit because it inits other parts of the system the app does not need.

**Comment by Nanquitas** [comment]
__appInit is already called before main by ctrulib so you don't have to call it. ;)

https://github.com/smealum/ctrulib/blob/master/libctru/source/system/stack_adjust.s#L26

**Comment by reworks-org** [comment]
ah, thanks. Fixed it in latest commit.
